
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 31 22:10:19 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int CONST = 5;
  public static final int LPARENTHESE = 37;
  public static final int ELSIF = 16;
  public static final int INTEGER = 43;
  public static final int SEMI = 40;
  public static final int ARRAY = 10;
  public static final int LESS = 27;
  public static final int MINUS = 23;
  public static final int NOT = 32;
  public static final int AND = 31;
  public static final int BIGEQ = 26;
  public static final int RECORD = 9;
  public static final int TYPE = 6;
  public static final int OR = 18;
  public static final int EOR = 44;
  public static final int COMMA = 41;
  public static final int DIV = 19;
  public static final int BEGIN = 3;
  public static final int LESSEQ = 28;
  public static final int ASSIGN = 33;
  public static final int IF = 14;
  public static final int DOT = 34;
  public static final int OF = 11;
  public static final int BOOLEAN = 42;
  public static final int EOF = 0;
  public static final int EQUAL = 30;
  public static final int error = 1;
  public static final int MUL = 24;
  public static final int ADD = 22;
  public static final int NUMBER = 46;
  public static final int MOD = 20;
  public static final int LSQBRACKET = 35;
  public static final int ERROR = 45;
  public static final int MODULE = 2;
  public static final int COLON = 39;
  public static final int ELSE = 17;
  public static final int RPARENTHESE = 38;
  public static final int WHILE = 12;
  public static final int BIG = 25;
  public static final int THEN = 15;
  public static final int RSQBRACKET = 36;
  public static final int END = 4;
  public static final int VAR = 7;
  public static final int PROCEDURE = 8;
  public static final int DO = 13;
  public static final int NOTEQ = 29;
  public static final int IDENTIFIER = 21;
}

